# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day06', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年纪'),
        ),
    ]
