# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(db_column='cate_name', max_length=30, verbose_name='分类名')),
                ('cate_num', models.CharField(max_length=20, null=True, verbose_name='分类编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名字')),
                ('barcode', models.CharField(max_length=13, null=True, verbose_name='条码')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='day02.Category')),
            ],
        ),
    ]
